baseURL = 'https://yu1lee.github.io/-/'
languageCode = 'en-us'
title = 'Hello Sichuan'
theme = 'ananke'
publishDir = "docs"
[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true


